// Generated by Wrangler on Wed Jun 19 2024 10:29:05 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
        ACCOUNT_ID: "b3304b14848de15c72c24a14b0cd187d";
        SERVICE_NAME: "agentic-browser";
        tail_consumers: [{"service":"agentic-browser-tail"}];
        OPENAI_API_KEY: string;
        BROWSER_RENDERING_TOKEN: string;
        BROWSER: DurableObjectNamespace;
        BUCKET: R2Bucket;
        DB: D1Database;
        RATE_LIMITER: any;
        MYBROWSER: Fetcher;
        AI: Ai;

}
